code-1-6:code-1-6.c
	gcc -o code-1-6 code-1-6.c
code-1-5:code-1-5.c
	gcc -o code-1-5 code-1-5.c
code-1-4:code-1-4.c
	gcc -o code-1-4 code-1-4.c
code-1-3:code-1-3.c
	gcc -o code-1-3 code-1-3.c
code-1-2:code-1-2.c
	gcc -o code-1-2 code-1-2.c
code-1-1:code-1-1.c
	gcc -o code-1-1 code-1-1.c
code-0-1:code-0-1.c
	gcc -o code-0-1 code-0-1.c
